# Generated by Django 3.1.6 on 2021-02-23 00:12

import datetime
from django.db import migrations, models
import django.db.models.deletion
import embed_video.fields
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('conditions', models.TextField(blank=True, verbose_name='Условия')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='cinema_logos', verbose_name='Логотип')),
                ('top_banner', models.ImageField(upload_to='cinema_banners', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Кинотеатр',
                'verbose_name_plural': 'Кинотеатры',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('description', models.TextField(verbose_name='Описание')),
                ('poster', models.ImageField(upload_to='posters/%Y/%m/%d/', verbose_name='Постер')),
                ('trailer', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='Трейлер')),
                ('screen_types', multiselectfield.db.fields.MultiSelectField(choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'IMAX')], max_length=10, verbose_name='Типы кино')),
                ('premier', models.DateField(default=datetime.date.today, verbose_name='Дата премьеры')),
                ('on_screen', models.BooleanField(default=True, verbose_name='В прокате')),
                ('year', models.PositiveIntegerField(default=2021, verbose_name='Год выпуска')),
                ('country', models.CharField(default='USA', max_length=100, verbose_name='Страна')),
                ('actors', models.CharField(blank=True, max_length=1000, verbose_name='Актеры')),
                ('age', models.CharField(default='6+', max_length=3, verbose_name='Возраст')),
                ('genre', models.ManyToManyField(related_name='related_genres', to='movie_app.Genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('top_banner', models.ImageField(upload_to='hall_banners', verbose_name='Фото')),
                ('scheme', models.ImageField(upload_to='hall_scheme', verbose_name='Схема')),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movie_app.cinema')),
            ],
            options={
                'verbose_name': 'Зал',
                'verbose_name_plural': 'Залы',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gallery')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галереи',
            },
        ),
    ]
