# Generated by Django 3.1.6 on 2021-02-16 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mama',
        ),
        migrations.DeleteModel(
            name='Try',
        ),
    ]
