# Generated by Django 3.1.6 on 2021-02-24 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinema',
            name='top_banner',
            field=models.ImageField(upload_to='cinema_banners', verbose_name='Верхний баннер'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='top_banner',
            field=models.ImageField(upload_to='hall_banners', verbose_name='Верхний баннер'),
        ),
    ]
