# Generated by Django 3.1.6 on 2021-02-27 15:40

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20210224_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='title', unique=True, verbose_name='URL'),
        ),
    ]
