# Generated by Django 3.1.6 on 2021-02-16 17:53

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_auto_20210216_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='screen_types',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('3D', '3D'), ('2D', '2D'), ('IMAX', 'IMAX')], default='2D', max_length=10, verbose_name='Типы кино'),
            preserve_default=False,
        ),
    ]
