# Generated by Django 3.1.6 on 2021-02-21 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_auto_20210219_2329'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='on_screen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movie',
            name='premier',
            field=models.DateField(default=datetime.date(2021, 3, 7)),
        ),
    ]
