# Generated by Django 3.1.6 on 2021-02-21 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0006_auto_20210221_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='premier',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата премьеры'),
        ),
    ]
