# Generated by Django 3.1.6 on 2021-02-21 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_auto_20210221_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='actors',
            field=models.CharField(blank=True, max_length=1000, verbose_name='Актеры'),
        ),
        migrations.AddField(
            model_name='movie',
            name='age',
            field=models.CharField(default='6+', max_length=3, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='movie',
            name='country',
            field=models.CharField(default='USA', max_length=100, verbose_name='Страна'),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(default=2021, verbose_name='Год выпуска'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
